MVC/Controllers/RubrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NEGOCIOS;
using ENTIDADES;
using MVC.Models;

namespace MVC.Controllers
{
    public class RubrosController : Controller
    {

      

        //PROBAR ARMAR CON EL MODEL ACA AFUERA

        // GET: Rubros
        public ActionResult Index()
        {
            RubrosModel Modelo = new RubrosModel();
            RubrosBL objNeg = new RubrosBL();

            Modelo.rubros = objNeg.ListarRubros();
            return View(Modelo);
        }
        //VISTA INDEX LISTA, HAY QUE SEGUIR CON DETALLES, Y UA VEZ TERINADAS TODAS, RETOMAR CLIENTES CREAR, PARA PODER REPLICAR EL DROPDOWN LIST DE RUBROS AL CREAR UN CLIENTE


        // GET: Rubros/Details/5
        public ActionResult Details(int id)
        {
            RubrosModel Modelo = new RubrosModel();
            RubrosBL objNeg = new RubrosBL();

            Modelo.Rubro = objNeg.GetRubros(id);
            return View(Modelo);
        }

        // GET: Rubros/Create
        public ActionResult Create()
        {
            RubrosModel Modelo = new RubrosModel();
            Modelo.Rubro = new Rubros();


            return View(Modelo);
        }

        // POST: Rubros/Create
        [HttpPost]
        public ActionResult Create(RubrosModel rub)
        {
            RubrosBL objNeg = new RubrosBL();

            try
            {
                if (rub.Rubro.Nombre == null)
                {
                    ModelState.AddModelError("", "Error, debe ingresar un nombre");
                    return View(rub);
                }

                objNeg.Crear(rub.Rubro);

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("Ocurrio un error al intentar agregar un rubro", ex.Message);          
                return View(rub);
            }
        }

        // GET: Rubros/Edit/5
        public ActionResult Edit(int id) //WORKS
        {

            RubrosModel Modelo = new RubrosModel();
           

            Modelo.Rubro = new RubrosBL().GetRubros(id);
            

            return View(Modelo);


        }


        //SEGUIR ACA

        // POST: Rubros/Edit/5
        [HttpPost]
        public ActionResult Edit(RubrosModel rub)
        {
           

            try
            {
                RubrosBL objNeg = new RubrosBL();
                if (rub.Rubro.Nombre == null)
                {
                    ModelState.AddModelError("", "Error, el nombre no puede estar vacio");
                    return View(rub);
                }

                objNeg.Editar(rub.Rubro);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("Ocurrio un error al intentar modificar un rubro", ex.Message);
                return View();
            }
        }



        // GET: Rubros/Delete/5
        public ActionResult Delete(int? id)
        {
            RubrosModel Modelo = new RubrosModel();
            RubrosBL objNeg = new RubrosBL();

            Modelo.Rubro = objNeg.GetRubros(id.Value);
            return View(Modelo);
        }

        // POST: Rubros/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {

            try
            {
                RubrosBL objNeg = new RubrosBL();
                objNeg.Eliminar(id);

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("Ocurrio un error al intentar eliminar el rubro.", ex.Message);
                return View();
            }
        }


    
    }
}

MVC/Views/Rubros/Create.cshtml
@model MVC.Controllers.RubrosModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Rubros", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RubrosModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(m => m.Rubro.Id)

      <div class="form-group">
          <h5 class="control-label col-lg-3">Nombre del Rubro</h5>
          @Html.TextBoxFor(model => model.Rubro.Nombre, htmlAttributes: new { @class = "form-control"} )
      </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC/Views/Rubros/Delete.cshtml
@model MVC.Controllers.RubrosModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rubros</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(m => m.Rubro.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(m => m.Rubro.Nombre)
        </dd>
        <dt>
            Código de Rubro
        </dt>
        <dd>
            @Html.DisplayNameFor(m => m.Rubro.Id)
        </dd>

    </dl>

    


    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC/Views/Rubros/Details.cshtml
@model MVC.Controllers.RubrosModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles</h2>

<div>
    <h4>RubrosModel</h4>
    <hr />
    <dl class="dl-horizontal">

        <div class="form-control-static">
            <dt>
                Rubro
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Rubro.Nombre)
            </dd>
        </div>

        <div class="form-control-static">
            <dt>
                Codigo del Rubro
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Rubro.Id)
            </dd>
        </div>


    </dl>
</div>

<p>
    @Html.ActionLink("Editar", "Edit", new {  id = Model.Rubro.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC/Views/Rubros/Edit.cshtml
@model MVC.Controllers.RubrosModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Rubros" ))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RubrosModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.Rubro.Id)

        <div class="form-group">

            <div class="col-md-10">
                @Html.EditorFor(m => m.Rubro.Nombre, new { HtmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.Rubro.Nombre, "", new {@class = "text- danger" })
            </div>

        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC/Views/Rubros/Index.cshtml
@model MVC.Controllers.RubrosModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Rubros</h2>

<p>
    @Html.ActionLink("Agregar Rubro", "Create", "Rubros", new { @class = "btn btn-primary" })
</p>

<table  class="table" id="dem">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Rubro.Nombre)
            </th>
            <th>
                Numero de Rubro
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.rubros)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>


                <td>
                    <a class="btn btn-primary btn-xs" title="Editar" href="@Url.Action("Edit", "Rubros", new { id = item.Id })"><i class="glyphicon glyphicon-edit"></i></a>

                    <a class="btn btn-success btn-xs" title="Detalles" href="@Url.Action("Details", "Rubros", new { id = item.Id })"><i class="glyphicon glyphicon-file"></i></a>

                    <a class="btn btn-danger btn-xs" title="Eliminar" href="@Url.Action("Delete", "Rubros", new { id = item.Id })"><i class=" glyphicon glyphicon-trash"></i></a>
                </td>

            </tr>
        }
    </tbody>


</table>


@section scripts
    {



    <script>

        $(document).ready(function () {
            $('#dem').DataTable();
        });

    </script>

}