MVC/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NEGOCIOS;
using MVC.Models;
using System.ComponentModel.DataAnnotations;

namespace MVC.Controllers
{
    public class ClientsController : Controller
    {

        // GET: Clients
        public ActionResult Index()
        {
            ClientesModel modelo = new ClientesModel();
            modelo.ListaClientes = new ClientesBL().ListarClientes();




            return View(modelo);
        }



        // GET: Clients/Details/5
        public ActionResult Details(int id)
        {
            ClientesModel Modelo = new ClientesModel();
            ClientesBL ClientesBao = new ClientesBL();
            //Para esto hice un metodo porque quiero devolver el pais, y esta tabla tiene 3 tablas entre medio con Clientes.
            Modelo.Cliente = ClientesBao.ObtenerDetalles(id);
            Modelo.Pais = ClientesBao.DevolverPais(id);


            ClientesDireccionesBL ClientesDireccionesBao = new ClientesDireccionesBL();
            Modelo.ListaDirecciones = ClientesDireccionesBao.ListarDireciones();


            MailsBL BaoMails = new MailsBL();
            Modelo.Cliente.Mails = BaoMails.ListaMails().Where(m => m.ClienteId == id).ToList();


            return View(Modelo);
        }







        // GET: Clients/Create
        public ActionResult Create()
        {
            ClientesModel Modelo = new ClientesModel();

            Modelo.ListaRubros = new RubrosBL().ListarRubros();

            CiudadesBL BaoCiudades = new CiudadesBL();
            Modelo.ListaCiudades = BaoCiudades.ListarCiudades();

            FuentesContactosBL BaoFuentesContactos = new FuentesContactosBL();
            Modelo.ListaFuentes = BaoFuentesContactos.ListaFuentes();
       

            return View(Modelo);
        }





        // POST: Clients/Create
        [HttpPost]
        public ActionResult Create(ClientesModel clienteNuevo)  //Para agregar/crear nos vamos a manejar con un solo registro de los que no sean tan imperativos, luego lo trabajamos desde el edit.
        {
            try
            {
                if (
                    clienteNuevo.Cliente.Nombre == null ||
                    clienteNuevo.Cliente.Apellido == null ||
                    clienteNuevo.Cliente.RubroId == null ||
                    clienteNuevo.Cliente.FechaNacimiento == null
                    )
                {
                    ModelState.AddModelError("", "Llene todos los campos adecuadamente.");
                }

                //Paso los datos al Modelo base
                if (clienteNuevo.FuentesSeleccionadas != null)
                {
                    foreach (var item in clienteNuevo.FuentesSeleccionadas)
                    {

                        clienteNuevo.Cliente.ClientesFuentesContacto.Add(new ENTIDADES.ClientesFuentesContacto()
                        {
                            ClienteId = clienteNuevo.Cliente.Id,
                            FuenteContactoId = item
                        });

                    }
                    //Esto funciona, ahora la pregunta es por que no me  lo guarda directamente desde la vista? Tal vez porque en client.Cliente.ClientesFuentesContacto es una lista comun?
                }

                if (clienteNuevo.Direccion != null) //eventualmente voy a tener que crear una lista de direcciones para guardar mas de una
                {
                    clienteNuevo.Cliente.ClientesDirecciones.Add(clienteNuevo.Direccion);
                }


                //Todos estos ifs despues voy a tenerque cambiarlos por algo que tome listas del controlador probablemente
                if (clienteNuevo.ClienteTelefono != null)
                {
                    clienteNuevo.Cliente.ClientesTelefonos.Add(clienteNuevo.ClienteTelefono);
                }


                
                if (clienteNuevo.ClienteMail != null)
                {
                    clienteNuevo.Cliente.Mails.Add(clienteNuevo.ClienteMail);
                }


                //aseguremonos de que esta todo siendo filtrado al clienteNuevo.Cliente
                ClientesBL BaoClientes = new ClientesBL();
                BaoClientes.Agregar(clienteNuevo.Cliente);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Ha surgido un imprevisto, revise la logica de la aplicacion", ex);
                return View(clienteNuevo);
            }
        }





        // GET: Clients/Edit/5
        public ActionResult Edit(int id)
        {
            ClientesModel Modelo = new ClientesModel();
            ClientesBL BaoClientes = new ClientesBL();

            Modelo.Cliente = BaoClientes.ObtenerDetalles(id);
            Modelo.ListaClientes = new ClientesBL().ListarClientes();
            Modelo.ListaRubros = new RubrosBL().ListarRubros();
       
            ClientesTelefonosBL BaoClientesTelefonos = new ClientesTelefonosBL();
            Modelo.Agenda = BaoClientesTelefonos.ListarTelefonos().Where(m => m.ClienteId == id).ToList(); 

            FuentesContactosBL BaoFuentesContactos = new FuentesContactosBL();
            Modelo.ListaFuentes = BaoFuentesContactos.ListaFuentes();
        
            MailsBL BaoMails = new MailsBL();
            Modelo.EmailsEditados = BaoMails.ListaMails().Where(m => m.ClienteId == id).ToList();

            CiudadesBL BaoCiudades = new CiudadesBL();
            Modelo.ListaCiudades = BaoCiudades.ListarCiudades();

            RubrosBL BaoRubros = new RubrosBL();
            Modelo.Domicilios = Modelo.Cliente.ClientesDirecciones.ToList();  

            return View(Modelo);
        }




        // POST: Clients/Edit/5 //Y si pruebo usando una lsita de mails desde la capa mails?
        [HttpPost]
        public ActionResult Edit(ClientesModel client)
        {
            try
            {
                if (
                    client.Cliente.Nombre == null ||
                    client.Cliente.Apellido == null ||
                    client.Cliente.RubroId == null ||
                    client.Cliente.FechaNacimiento == null
                    )
                {
                    ModelState.AddModelError("", "Para realizar los cambios no pueden haber campos vacíos.");
                }

                ClientesBL BaoClientes = new ClientesBL();
                MailsBL BaoMails = new MailsBL();

                //vamos a tratar de pasarlos como client.Cliente.ClientesFuentesCOntactos asi puedo eliminar un campo del model (obviamente para poder ahcer esto, si logro hacer esto aca voy a tner que replicarlo en el create porque lo tengo qhecho de la otra forma)
                //quiero pasar los datos de fuentesSelected al client.Cliente asi envio menos cosas a la bl. Aunque tal vez valg la pena dejarlo como esta. Pero si cambiar los nombres para que sean mas legibles

                if (client.FuentesSeleccionadas != null)//CHEQUEAR PORQUE PENSE QUE LO ESTABA HACIENDOEN CREAR, NO SE SI ESTO ESTA BIEN
                {
                    foreach (var item in client.FuentesSeleccionadas)
                    {

                        client.Cliente.ClientesFuentesContacto.Add(new ENTIDADES.ClientesFuentesContacto()
                        {
                            ClienteId = client.Cliente.Id,
                            FuenteContactoId = item
                        });

                    }                 
                }
                /*
                 Tengo que probar ahora que pasa si mando los datos sacando el parametro de fuentesSelected que se envia al bl, tambien tengo que modificar lo que sehace en el  DAL!! Si no funciona, borro esto y me quedo con el parametro que ya estoy enviando a parte de client
                 */




                //Paso los datos que se guardan en el modelo a la entidad asi puedo mandarlos al bl (esto seguramente peude simplificarse)
                if (client.Direccion.Calle != null || client.Direccion.Altura == null)   //Si tengo algo guardado en Direccion (individual nuevo)
                {
                    client.Cliente.ClientesDirecciones.Add(client.Direccion);
                }

                if (client.Domicilios != null)
                {
                    foreach (var antiguosRegistrosEditados in client.Domicilios)
                    {
                        client.Cliente.ClientesDirecciones.Add(antiguosRegistrosEditados);
                    }
                }

                //Mails
                //Filtro si estan llenos alguno de los dos campos, EmailsEditados o ClienteMail.Mail y los acomodo para poder enviarlos al BL.
                if (client.ClienteMail.Mail != null)
                {
                    client.Cliente.Mails.Add(client.ClienteMail);
                }
                if (client.EmailsEditados != null)
                {
                    foreach (var item in client.EmailsEditados)
                    {
                        client.Cliente.Mails.Add(item);
                    }
                }



                //Telefonos: Paso los resultados guardados de Agenda a client.Cliente.ClienteTelefonos
                if (client.Agenda != null)
                {              
                    foreach (var telefono in client.Agenda)
                    {
                        client.Cliente.ClientesTelefonos.Add(telefono);
                    }
                }

                if (client.ClienteTelefono.Telefono != null)
                {
                    client.Cliente.ClientesTelefonos.Add(client.ClienteTelefono);         
                }
               


                BaoClientes.Editar(client.Cliente, client.FuentesSeleccionadas);

                return RedirectToAction("Index");
            }
            catch (Exception ex)    //El error esta en clientesDirecciones -> ciudades
            {

MVC/Controllers/MailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


using NEGOCIOS;
using MVC.Models;

namespace MVC.Controllers
{
    public class MailsController : Controller
    {
        // GET: Mails
        public ActionResult Index()
        {
            MailsBL bao = new MailsBL();
            MailsModel mailModel = new MailsModel();
            mailModel.MailsLista = bao.ListaMails();

            ClientesBL cao = new ClientesBL();
            mailModel.ClientesLista = cao.ListarClientes();

            return View(mailModel);
        }

        // GET: Mails/Details/5
        public ActionResult Details(int id)
        {
            MailsBL bao = new MailsBL();
            MailsModel Modelo = new MailsModel();
            Modelo.Mails = bao.GetMails(id);

            return View(Modelo);
        }

        // GET: Mails/Create
        public ActionResult Create()
        {
            MailsModel mailModel = new MailsModel();

            ClientesBL cao = new ClientesBL();
            mailModel.ClientesLista = cao.ListarClientes();


            return View(mailModel);
        }

        // POST: Mails/Create
        [HttpPost]
        public ActionResult Create(MailsModel mailModel)
        {
            try
            {
                //Me estaba andando mal porque tenia esto
                /*
                  if (mailModel.Mails == 0) //tal vez el que no estuviese definiendo que atributo particular de Mails, me daba error. El identity se crea ya en la base de datos.
                 {
                     ModelState.AddModelError(mailModel.Mails.Mail, "Algun campo esta vacio.");
                 }
                  */

                MailsBL bao = new MailsBL();
                bao.Agregar(mailModel.Mails);

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "Surgio un error de tipo catch.");
                return View();
            }
        }

        // GET: Mails/Edit/5
        public ActionResult Edit(int id)
        {
            MailsModel Modelo = new MailsModel();
            MailsBL bao = new MailsBL();

            ClientesBL cao = new ClientesBL();
            Modelo.ClientesLista = cao.ListarClientes();

            Modelo.Mails = bao.GetMails(id);

            return View(Modelo);
        }

        // POST: Mails/Edit/5
        [HttpPost]
        public ActionResult Edit(MailsModel mail)
        {
            try
            {
                if (mail.Mails.Mail == null) {
                    ModelState.AddModelError("", "agregue un nombre");
                }

                MailsBL bao = new MailsBL();
                bao.Editar(mail.Mails);

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "error de tipo catch");
                return View();
            }
        }

        // GET: Mails/Delete/5
        public ActionResult Delete(int? id)
        {
            MailsModel Modelo = new MailsModel();
            MailsBL bao = new MailsBL();

            ClientesBL cao = new ClientesBL();


            Modelo.Mails = new MailsBL().GetMails(id.Value);
            Modelo.ClientesLista = cao.ListarClientes();

            return View(Modelo);
        }

        // POST: Mails/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                MailsBL bao = new MailsBL();
                bao.Eliminar(id);




                //return RedirectToAction("Index");

                /*
                MailsModel Modelo = new MailsModel();
                Modelo.Mails = bao.GetMails(id);
                var MailExistente = Modelo.Mails;
                if (MailExistente.ClienteId != null)
                {
                    return RedirectToRoute("VueltaDeMails");
                }
                else
                {
                    
                }
                */
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "Ha surgido un error de tipo catch");
                return View();
            }
        }
    }
}

MVC/Views/Clients/Delete.cshtml
@model MVC.Models.ClientesModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to delete this Cliente?</h3>
<div>
    <h4>Clients</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Apellido)

        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Rubros.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Rubros.Nombre)

        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Cliente.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.FechaNacimiento)
        </dd>

      






    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-xs " />


            <a class="btn btn-info btn-xs" href="@Url.Action("Index", "Clients")"><i class="glyphicon glyphicon-arrow-left"></i></a>
        </div>
    }
</div>

MVC/Views/Clients/Edit.cshtml
@model MVC.Models.ClientesModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Cliente</h2>

@using (Html.BeginForm("Edit", "Clients", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>
            @Html.DisplayFor(m => m.Cliente.Nombre) @Html.DisplayFor(m => m.Cliente.Apellido)
        </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.Cliente.Id)
        <div class="row ">

            <div class="col-lg-6">


                <div class="form-control-static  bg-info  img-rounded container-fluid nuevoDiv">
                    <dl class="form-control-static">
                        <dt>Nombre</dt>
                        <dd>
                            @Html.TextBoxFor(m => m.Cliente.Nombre, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Cliente.Nombre, "", new { @class = "text-danger" })
                        </dd>
                    </dl>

                    <dl class="form-control-static ">
                        <dt>Apellido</dt>
                        <dd>
                            @Html.TextBoxFor(m => m.Cliente.Apellido, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Cliente.Apellido, "", new { @class = "text-danger" })
                        </dd>
                    </dl>
                </div>

                <br />

                <dl class="form-control-static  bg-info  img-rounded container-fluid nuevoDiv">
                    <dt>Direccion</dt>

                    @if (Model.Domicilios != null)
                    {
                        for (int i = 0; i < Model.Domicilios.Count; i++)
                        {
                            <span>Ciudad</span>
                            @Html.DropDownListFor(m => m.Domicilios[i].CiudadId, new SelectList(Model.ListaCiudades, "Id", "Nombre", Model.Domicilios[i].CiudadId), htmlAttributes: new { @class = "form-control input-sm" })
                            <div class="form-group row">





                                <div class="col-sm-6">
                                    <span>Calle: </span>@Html.TextBoxFor(m => m.Domicilios[i].Calle, htmlAttributes: new { @class = "form-control input-sm" })
                                    <span>Altura: </span>@Html.TextBoxFor(m => m.Domicilios[i].Altura, htmlAttributes: new { @class = "form-control input-sm" })
                                </div>


                                <div class="col-sm-6">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <span>Piso</span>  @Html.EditorFor(model => model.Domicilios[i].Piso, new { htmlAttributes = new { @class = "form-control input-sm col-sm-6" } }) <br />
                                            <span>Dpto</span>  @Html.EditorFor(model => model.Domicilios[i].Dpto, new { htmlAttributes = new { @class = "form-control input-sm col-sm-6" } }) <br />
                                        </div>
                                    </div>
                                </div>


                            </div>


                            <div class="col-lg-3">
                                <span>Borrar</span>
                                <a class="btn btn-danger btn-sm" title="Eliminar" href="@Url.Action("Delete", "ClientesDirecciones", new { Model.Domicilios[i].Id, Model.Domicilios[i].ClienteId })"><i class=" glyphicon glyphicon-trash"></i></a>
                            </div>
                        }
                    }

                    <a href="#dom" data-toggle="collapse" class="btn btn-info">Agregar un domicilio</a>
                    <dl id="dom" class="collapse ">
                        <span>Ciudad</span>
                        @Html.DropDownListFor(m => m.Direccion.CiudadId, new SelectList(Model.ListaCiudades, "Id", "Nombre"), "Seleccione uno", htmlAttributes: new { @class = "form-control input-sm" })
                        <div class="row">


                            <div class="col-sm-6">
                                <span>Calle: </span>@Html.TextBoxFor(m => m.Direccion.Calle, htmlAttributes: new { @class = "form-control input-sm" })
                                <span>Altura: </span>@Html.TextBoxFor(m => m.Direccion.Altura, htmlAttributes: new { @class = "form-control input-sm" })
                            </div>

                            <div class="col-sm-6">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <span>Piso: </span>@Html.TextBoxFor(m => m.Direccion.Piso, htmlAttributes: new { @class = "form-control input-sm" })
                                        <span>Dpto: </span>@Html.TextBoxFor(m => m.Direccion.Dpto, htmlAttributes: new { @class = "form-control input-sm" })
                                    </div>
                                </div>
                            </div>
                        </div>

                    </dl>
                </dl>

                <br />

                <div class="form-control-static  bg-info  img-rounded col-lg-6 container-fluid nuevoDiv">
                    <dt>
                        Fecha de nacimiento (d/m/a)
                    </dt>
                    <dd>
                        @Html.TextBoxFor(m => m.Cliente.FechaNacimiento, new { @type = "datetime", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Cliente.FechaNacimiento, "", new { @class = "text-danger" })
                    </dd>
                </div>




            </div>
            <br />






            <div class="col-lg-5 ">

                <dl class="form-control-static  bg-info img-rounded  container-fluid nuevoDiv">

                    <dt>
                        Rubro
                    </dt>
                    <dd class="form-control-static ">
                        <div class="">
                            @foreach (var r in Model.ListaRubros.Where(m => m.Id == Model.Cliente.RubroId))
                            {
                                @Html.DropDownListFor(m => m.Cliente.RubroId, new SelectList(Model.ListaRubros, "Id", "Nombre"), "Seleccionar uno", htmlAttributes: new { @class = "form-control  input-sm" })
                                <!--Elimina el rubro, no el rubro correspondiente al cliente.--> <!--Me quede aca, no pude ver como pasar un parametro del client id aca para luego mandar al route. Puedo probar directamente hallar una forma en el controller de rubro. Pero lo idea seria ver una forma de pasarle un parametro de este id.-->
                                @Html.ValidationMessageFor(model => model.Cliente.RubroId, "", new { @class = "text-danger" })





                            }

                            @if (!Model.ListaRubros.Where(m => m.Id == Model.Cliente.RubroId).Any())
                            {
                                @Html.DropDownListFor(m => m.Cliente.RubroId, new SelectList(Model.ListaRubros, "Id", "Nombre"), "Seleccionar uno", htmlAttributes: new { @class = "form-control  input-sm" })
                            }


                        </div>



                    </dd>

                </dl>


                <br />

                <dl class="form-control-static bg-info  img-rounded container-fluid nuevoDiv">
                    <!--En el dal voy a tener que agregar, creo (o fijarme como hice con direcciones) el tema del campo ClienteId y CiudadId(No permite nulos)-->
                    <dt>
                        Telefono
                    </dt>
                    <dd>
                        @if (Model.Agenda != null)
                        {
                            for (int i = 0; i < Model.Agenda.Count; i++)
                            {
                                <div class="row">
                                    <div class="col-sm-5">
                                        <span>Numero</span> @Html.EditorFor(model => model.Agenda[i].Telefono, new { htmlAttributes = new { @class = "form-control form-control-sm", @type = "number" } })
                                    </div>
                                    <div class="col-sm-4">
                                        <span>Ciudad del numero</span> @Html.DropDownListFor(model => model.Agenda[i].CiudadId, new SelectList(Model.ListaCiudades, "Id", "Nombre", Model.Agenda[i].CiudadId), htmlAttributes: new { @class = "form-control  input-sm" })
                                    
                                    </div>
                                    
                                    <span>Borrar</span> <br />
                                        <a class="btn btn-danger btn-sm" title="Eliminar" href="@Url.Action("Delete", "ClientesTelefonos", new { n=Model.Agenda[i].Telefono, c=Model.Agenda[i].ClienteId })"><i class=" glyphicon glyphicon-trash"></i></a>
                                    
                                </div>
                            }
                        }
                        <br />
                        <a href="#tel" data-toggle="collapse" class="btn btn-info">Agregar un telefono</a>
                        <div id="tel" class="collapse row ">
                            <div class="col-sm-4">
                                <span>Numero</span> @Html.EditorFor(m => m.ClienteTelefono.Telefono, new { htmlAttributes = new { @class = "form-control input-sm", @type = "number" } })
                            </div>
                            <div class="col-sm-4">
                                <span>Caracteristica</span> @Html.DropDownListFor(model => model.ClienteTelefono.CiudadId, new SelectList(Model.ListaCiudades, "Id", "Nombre"), htmlAttributes: new { @class = "form-control  input-sm" })
                            </div>
                        </div>
                    </dd>
                </dl>

                <br />

                <dl class="form-control-static  bg-info  img-rounded container-fluid nuevoDiv">

                    <dt>
                        Mail
                    </dt>

                    <dd>
                        @if (Model.EmailsEditados != null)
                        {
                            for (int i = 0; i < Model.EmailsEditados.Count; i++)
                            {


                                <div class="row">
                                    <div class="col-lg-9">
                                        @Html.EditorFor(model => model.EmailsEditados[i].Mail, new { htmlAttributes = new { @class = "form-control form-control-sm", @type = "email" } })
                                    </div>
                                    <div class="col-lg-3">
                                        <span>Borrar</span>
                                        <a class="btn btn-danger btn-sm" title="Eliminar" href="@Url.Action("Delete", "Mails", new { Model.EmailsEditados[i].Id, Model.EmailsEditados[i].ClienteId })"><i class=" glyphicon glyphicon-trash"></i></a>
                                    </div>
                                
                                </div>
                                
                                
                                
                                <br />
                            }
                        }

                        <a href="#mail" data-toggle="collapse" class="btn btn-info">Agregar un mail</a>
                        <div id="mail" class="collapse">
                            <span>Mail</span> @Html.EditorFor(m => m.ClienteMail.Mail, new { htmlAttributes = new { @class = "form-control form-control-sm", @type = "email" } })
                        </div>
                    </dd>

                </dl>

                <br />

                <div class="form-control-static  bg-info  img-rounded container-fluid nuevoDiv">

                    <div class="row">
                        <dt class="col-sm-4">Fuentes de contacto</dt>

                        <dd class="col-sm-3">
                            @foreach (var item in Model.Cliente.ClientesFuentesContacto)
                            {

                                @Html.DisplayFor(modelItem => item.FuentesContacto.Nombre) <br />

                            }
                        </dd>
                    </div>
                    <br />
                    <a href="#fuente" data-toggle="collapse" class="btn btn-info">Cambiar fuente</a>
                    
                    <dd id="fuente" class="collapse">
                       <br />
                        @Html.ListBoxFor(m => m.FuentesSeleccionadas, new SelectList(Model.ListaFuentes, "Id", "Nombre"), htmlAttributes: new { @class = "form-control" })
                       
                    </dd>

                </div>
            </div>







        </div>
    </div>

    <br />
    <div class="col-lg-4">
        <a class=" btn btn-group-sm btn-lg center-block " title="Index" href="@Url.Action("Index", "Clients", null)">
            Volver al Inicio
        </a>
    </div>

    <div class="col-lg-4">
        <input type="submit" value="Save" class="btn btn-success btn-lg center-block">
    </div>


    <div class="col-lg-4">
        <a class=" btn btn-group-sm btn-lg center-block" title="Detalles" href="@Url.Action("Details", "Clients", new { id = Model.Cliente.Id })">
            Volver a Detalles
        </a>
    </div>

    <br />

}