MVC/Controllers/PaisesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows;
using MVC.Models;
using NEGOCIOS;

namespace MVC.Controllers
{
    public class PaisesController : Controller
    {



        PaisesBL objNeg = new PaisesBL();


        // GET: Paises
        public ActionResult Index()
        {

            PaisesModel Modelo = new PaisesModel();
            Modelo.Paises = objNeg.ListarPaises();


            ProvinciasBL ModeloPRO = new ProvinciasBL();
            Modelo.provincies = ModeloPRO.ListarProvincias();

            return View(Modelo);
        }




        public ActionResult GetPais(int id)
        {
            //PaisesBL paiNeg = new PaisesBL();
            PaisesModel Modelo = new PaisesModel();

            Modelo.Pais = objNeg.GetPaises(id);
            //Modelo.country = paiNeg.ListarPaises();

            return View(Modelo);
        }



        public ActionResult Crear()
        {

            //Declaracion de capa de negocios (Necesitaremos las ciudades)
            PaisesBL paiNeg = new PaisesBL();

            //Declaracion del Modelo de MVC
            PaisesModel moodelo = new PaisesModel();

            //Accedemos 
            //moodelo.country = paiNeg.ListarPaises();

            return View(moodelo);
            //
            //Hasta aca, la vista esta perfecta. Se replican adecuadamente los paises.
        }



        [HttpPost]
        public ActionResult Crear(PaisesModel paises) //Clase Modelo de MVC
        {

            try
            {


                if (paises.Pais.Nombre == null)
                {
                    ModelState.AddModelError("", "Error, debe ingresar un nombre");
                    return View(paises);
                }


               


                objNeg.Crear(paises.Pais);
                //La propiedad provi.Provincia es la que acabo de declarar que me dijiste vos en el Model de MVC

                return RedirectToAction("Index");


            }
            catch (Exception ex)
            {
                //ModelState.AddModelError("Ocurrio un error al intentar agregar una pais, tal vez ya exista", ex.Message);
                ModelState.AddModelError("", "El pais ya esta en la base de datos");
                return View(paises);
            }

        }





        // GET: Provincias/Edit/5
        public ActionResult Editar(int id) //W GB
        {
            //PaisesBL paiNeg = new PaisesBL();
            PaisesModel Modelo = new PaisesModel();

            Modelo.Pais = objNeg.GetPaises(id);
            //Modelo.country = paiNeg.ListarPaises();

            return View(Modelo);

        }



        // POST: Provincias/Edit/5
        [HttpPost]
        public ActionResult Editar(PaisesModel paises) //W GB
        {
            try
            {
                

                if (paises.Pais.Nombre == null)
                {
                    ModelState.AddModelError("", "Error, debe ingresar un nombre");
                    return View(paises);
                }

                    objNeg.Editar(paises.Pais);
                    

            }
            catch (Exception ex)
            {
               
                /*
                 Actualmente el ciclo es este:
                 Evalua si es nulo.
                 Si no es nulo intenta registrarlo.
                 Por alguna razon si el nombre ya esta registrado, entra en el catch el ciclo.
                 Ahora no entiendo como que es que asocia el nombre al Id.
                 */

                MessageBox.Show("En pais ya se enceuntra registrado, no puede dubplicar el registro");
                return View(paises);
            }

            

            return RedirectToAction("Index");
        }




        

        // GET: Provincias/Delete/5
        public ActionResult Eliminar(int? id)
        {
            //PaisesBL paiNeg = new PaisesBL();
            PaisesModel Modelo = new PaisesModel();

            Modelo.Pais = objNeg.GetPaises(id.Value);
            //Modelo.country = paiNeg.ListarPaises();

            return View(Modelo);

            
        }

        // POST: Provincias/Delete/5
        [HttpPost]
        public ActionResult Eliminar(int id)
        {
            try
            {
                objNeg.Eliminar(id);
                return RedirectToAction("Index");
            }
            catch
            {

                return View();
            }
        }





    }
}

MVC/Views/Paises/Crear.cshtml
@model MVC.Models.PaisesModel

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear</h2>

@using (Html.BeginForm("Crear", "Paises", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Nuevo Pais</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Pais.Id)

        <div class="form-group">
            <h5 class="control-label col-lg-3">Nombre Pais</h5>
            @Html.TextBoxFor(m => m.Pais.Nombre, htmlAttributes: new { @class = "form-control" })

        <div class="col-md">

            
            @Html.ValidationMessageFor(model => model.Pais.Nombre, "", new { @class = "text-danger" })
        </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info btn-xs" />

                <a class="btn btn-info btn-xs" href="@Url.Action("Index", "Paises")"><i class="glyphicon glyphicon-arrow-left"></i></a>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC/Views/Paises/Editar.cshtml
@model MVC.Models.PaisesModel

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>

@using (Html.BeginForm("Editar", "Paises", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>PaisesModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Pais.Id)
    <div class="form-group">
        @Html.TextBoxFor(m => m.Pais.Nombre, htmlAttributes: new { @class = "form-control" })
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC/Views/Paises/Eliminar.cshtml
@model MVC.Models.PaisesModel

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Provincias</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pais.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais.Id)

        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-xs " />


            <a class="btn btn-info btn-xs" href="@Url.Action("Index", "Paises")"><i class="glyphicon glyphicon-arrow-left"></i></a>
        </div>
    }
</div>

MVC/Views/Paises/GetPais.cshtml
@model MVC.Models.PaisesModel

@{
    ViewBag.Title = "GetPais";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetPais</h2>

<div>
    <h4>ProvinciasModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pais.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais.Nombre)
        </dd>




        <dt>
            @Html.DisplayNameFor(model => model.Pais.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais.Id)

        </dd>


     

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Pais.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC/Views/Paises/Index.cshtml
@model MVC.Models.PaisesModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Paises Index</h2>
<p>
    @Html.ActionLink("Crear nueva", "Crear", "Paises", new { @class = "btn btn-primary" })
</p>
<table class="table" id="dem">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pais.Nombre)
            </th>
            <th>
                Codigo de Pais

                    
            </th>
            <th>

            </th>

            <th>




            </th>
            <th></th>
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model.Paises)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>

                    @Html.DisplayFor(modelItem => item.Id)

                </td>
                <td>
                </td>

                <td>
                </td>

                <td>
                    <a class="btn btn-primary btn-xs" title="Editar" href="@Url.Action("Editar", "Paises", new { id = item.Id })"><i class="glyphicon glyphicon-edit"></i></a>

                    <a class="btn btn-success btn-xs" title="Detalles" href="@Url.Action("GetPais", "Paises", new { id = item.Id })"><i class="glyphicon glyphicon-file"></i></a>

                    <a class="btn btn-danger btn-xs" title="Eliminar" href="@Url.Action("Eliminar", "Paises", new { id = item.Id })"><i class=" glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
        }

    </tbody>


</table>


@section scripts
    {



    <script>

        $(document).ready(function () {
            $('#dem').DataTable();
        });

    </script>

}